name: opencv_measurement_plugin
description: Real-time object measurement plugin with OpenCV for Flutter desktop applications. No external DLL required.
version: 1.0.0
homepage: https://github.com/your-username/opencv_measurement_plugin
repository: https://github.com/your-username/opencv_measurement_plugin
issue_tracker: https://github.com/your-username/opencv_measurement_plugin/issues
documentation: https://pub.dev/packages/opencv_measurement_plugin

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      windows:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      linux:
        ffiPlugin: true

topics:
  - opencv
  - computer-vision
  - object-detection
  - measurement
  - camera