name: opencv_measurement_plugin
description: Real-time object measurement plugin with OpenCV for Flutter desktop applications. No external DLL required.
version: 1.0.3
homepage: https://github.com/permpree-vornthaisong/opencv_measurement_plugin
repository: https://github.com/permpree-vornthaisong/opencv_measurement_plugin
issue_tracker: https://github.com/permpree-vornthaisong/opencv_measurement_plugin/issues
documentation: https://pub.dev/packages/opencv_measurement_plugin

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.0
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      windows:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      linux:
        ffiPlugin: true

  # Bundle all DLL files as assets
  assets:
    - windows/measurement_library.dll
    - windows/opencv_core4.dll
    - windows/opencv_imgproc4.dll
    - windows/opencv_imgcodecs4.dll
    - windows/opencv_videoio4.dll
    - windows/jpeg62.dll
    - windows/libpng16.dll
    - windows/tiff.dll
    - windows/zlib1.dll
    - windows/liblzma.dll
    - windows/libsharpyuv.dll
    - windows/libwebp.dll
    - windows/libwebpdecoder.dll
    - windows/libwebpdemux.dll
    - windows/libwebpmux.dll

topics:
  - opencv
  - computer-vision
  - object-detection
  - measurement
  - camera